# TODO: join with ./opengl-test.sh script and allow passing arguments
MANGOHUD_CONFIG=\
gpu_text=GPU,\
gpu_temp,\
gpu_power,\
gpu_core_clock,\
gpu_mem_clock,\
gpu_load_change,\
cpu_text=CPU,\
cpu_temp,\
cpu_power,\
cpu_mhz,\
cpu_load_change,\
core_load,\
core_load_change,\
io_stats,\
io_read,\
io_write,\
vram,\
ram,\
swap,\
procmem,\
procmem_shared,\
procmem_virt,\
battery,\
battery_icon,\
gamepad_battery,\
gamepad_battery_icon,\
fps,\
fps_sampling_period=500,\
fps_color_change,\
fps_value=30+60,\
frametime,\
frame_count,\
engine_version,\
gpu_name,\
vulkan_driver,\
wine,\
arch,\
frame_timing,\
histogram,\
gamemode,\
vkbasalt,\
show_fps_limit,\
resolution,\
font_size=32,\
font_scale=1.0,\
font_size_text=32,\
font_scale_media_player=0.55,\
no_small_font,\
position=center,\
table_columns=4,\
background_alpha=0.5,\
alpha=0.5,\
benchmark_percentiles=97+AVG+1+0+1\
offset_x=0,\
offset_y=0 \
mangohud vkcube --width 1920 --height 1080
